version: "3.8"
services:
  web:
    container_name: web
    restart: unless-stopped
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8090:80"
    volumes:
      - ./web/html:/var/www/html
    environment:
      MYSQL_HOST: 'web-database'
      MYSQL_USER_ROOT: 'root'
      MYSQL_PASSWORD_ROOT: oo4byfw4dquhbarfvwgdhsuaoxnrc
      MYSQL_DATABASE: database
      MYSQL_USER: database_user
      MYSQL_PASSWORD: f3ebvua4dgyhuotbsvgaxojirwncte
    depends_on:
      - "web-database"
  web-database:
    container_name: web-database
    image: mysql:latest
    volumes:
      - web-db-data:/var/lib/mysql
    ports:
      - "3310:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: oo4byfw4dquhbarfvwgdhsuaoxnrc
      MYSQL_DATABASE: database
      MYSQL_HOST: '%'
      MYSQL_USER: database_user
      MYSQL_PASSWORD: f3ebvua4dgyhuotbsvgaxojirwncte
volumes:
  web-db-data: {}

